<?php

namespace BiblioBundle\Repository;

/**
 * AvisNegRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisNegRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findvote($idUser, $livre)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('DELETE FROM BiblioBundle:AvisNeg R WHERE R.livre = :id AND R.ideleve = :ideleve');
        $dql->setParameter(':id',$livre)
            ->setParameter(':ideleve', $idUser)
            ->setMaxResults(1);
        return $dql->getResult();
    }
}
