<?php

namespace BiblioBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;

/**
 * ReservationlivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationlivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindme($idUser, $idLivre)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('SELECT R FROM BiblioBundle:Reservationlivre R WHERE R.idlivre = :idlivre AND R.ideleve = :ideleve');
        $dql->setParameter(':idlivre',$idLivre)
            ->setParameter(':ideleve', $idUser);
        return $dql->getResult();
    }

    public function findByUser($idc){
        $query=$this->getEntityManager()->createQuery("SELECT r from BiblioBundle:Reservationlivre r where r.id ='$idc'");
        return $query->getResult();
    }



}
