biblio_homepage:
    path:     /
    defaults: { _controller: BiblioBundle:Default:index }

ajoutLivre:
    path:     /ajoutLivre
    defaults: { _controller: BiblioBundle:Livres:AjoutLivre }

AfficheLivre:
    path:     /AfficheLivre
    defaults: { _controller: BiblioBundle:Livres:AfficheLivre }

AfficheLivreF:
    path:     /AfficheLivreF
    defaults: { _controller: BiblioBundle:Livres:AfficheLivreF }

UpdateLivre:
    path: /UpdateLivre/{id}
    defaults: {_controller: BiblioBundle:Livres:UpdateLivre}

DeleteLivre:
    path: /DeleteLivre/{id}
    defaults: {_controller: BiblioBundle:Livres:DeleteLivre}

ReservationLivre:
    path:     /ReservationLivre/{idLivre}
    defaults: { _controller: BiblioBundle:Livres:ReservationLivre }

getLivre:
    path:     /getLivre/{idLivre}
    defaults: { _controller: BiblioBundle:Livres:getLivre }

RendreLivre:
    path:   /RendreLivre/{idLivre}
    defaults: { _controller: BiblioBundle:Livres:RendreLivre }


Delete:
    path: /Delete/{id}
    defaults: {_controller: BiblioBundle:Type:Delete}


Update:
    path: /Update/{id}
    defaults: {_controller: BiblioBundle:Type:Update}


AfficheType:
    path: /AfficheType
    defaults: {_controller: BiblioBundle:Type:AfficheType}


AjoutType:
    path: /AjoutType
    defaults: {_controller: BiblioBundle:Type:AjoutType}

sandbox_pdfexample:
    path:     /pdf-example
    defaults: { _controller: BiblioBundle:Livres:pdf }

reservation_read_User:
    path:     /readMyReservation
    defaults: { _controller: BiblioBundle:Livres:reserveReadByUser }

dislikeL:
    path:     /dislike{id}
    defaults: { _controller: BiblioBundle:Livres:dislike }

like:
    path:     /like{id}
    defaults: { _controller: BiblioBundle:Livres:like }

ImpLivre:
    path:     /imp
    defaults: { _controller: BiblioBundle:Livres:imp }
    methods:  GET

Stat:
    path:     /Stat
    defaults: { _controller: BiblioBundle:Livres:Stat }