user_homepage:
  path:     /
  defaults: { _controller: UserBundle:Default:index }
user_admin:
  path:     /access/admin
  defaults: { _controller: UserBundle:Default:admin }
user_parent:
  path:     /access/parent
  defaults: { _controller: UserBundle:Default:parent }


user_eleve:
  path:     /access/eleve
  defaults: { _controller: UserBundle:Default:eleve}
user_elevee:
    path:     /access/elevee/{id}
    defaults: { _controller: UserBundle:Default:elevee }
user_elevea:
    path:     /access/elevea/{id}
    defaults: { _controller: UserBundle:Default:elevea }
user_enseignant:
  path:     /access/enseignant
  defaults: { _controller: UserBundle:Default:enseignant }
club:
  path:     /access/club
  defaults: { _controller: UserBundle:Default:club  }
home:
  path:     /home
  defaults: { _controller: UserBundle:Default:home }
session:
  path:     /home
  defaults: { _controller: FosUserBundle:Default:security }

StatIndexBP:
  path:     /access/stat
  defaults: { _controller: BiblioBundle:Livres:StatIndexBP }

_afficherReservation:
  path:     /AfficheReservation
  defaults: { _controller: ClubBundle:Reservation:AfficheReservation }